- block:

  - name: set user.name
    git_config: name=user.name scope=global value="{{ name }}"

  - name: set user.email
    git_config: name=user.email scope=global value="{{ email }}"

  tags:
    - git
