- block:

  - name: homebrew update
    homebrew:
      update_homebrew: true

  - name: homebrew package install
    homebrew:
      name: "{{ item.name }}"
      state: "{{ item.state | default('present') }}"
    with_items: "{{ packages }}"

  - name: install cask packages
    homebrew_cask:
      name={{ item.name }}
      state={{ item.state | default('installed') }}
    with_items: "{{ homebrew_cask_packages }}"

  tags:
    - homebrew
